apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/kubevirt/kubevirt
    targetRevision: v1.1.0
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kubevirt
  syncPolicy:
    automated: {}