apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/k8snetworkplumbingwg/multus-cni
    targetRevision: master
    path: deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: {}