apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          interfaces:
            - name: default
              masquerade: {}
            - name: vlan100
              bridge: {}
          disks:
            - name: containerdisk
              disk:
                bus: virtio
        resources:
          requests:
            memory: 512Mi
      networks:
        - name: default
          pod: {}
        - name: vlan100
          multus:
            networkName: vlan100
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo